[package]
name = "persist_memory_test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
minicbor = { features = ["derive", "alloc"] }
persist_memory = { path = "../persist_memory" }
